### 使用YOLOv5模型進行物件偵測後，物件的Bounding Box座標、信心指數、類別等資訊可以pandas dataframe格式取出來使用
### 本程式碼為熟悉如何取得pandas dataframe內的資訊，方便之後做物體追蹤時調整參數使用

In [1]:
import torch
import torchvision

print(torch.__version__)
print('CUDA available: ' + str(torch.cuda.is_available()))
print('cuDNN version: ' + str(torch.backends.cudnn.version()))
print(torchvision.__version__)

1.8.0
CUDA available: True
cuDNN version: 8000
0.9.0


In [2]:
# 載入自行訓練的 YOLOv5 模型
model = torch.hub.load('ultralytics/yolov5', 'custom', path='./models/yolov5s62best.pt', force_reload=True)

# 設定 IoU 門檻值
model.iou = 0.3

# 設定信心門檻值
model.conf = 0.5


Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to /root/.cache/torch/hub/master.zip
YOLOv5 🚀 2022-9-28 Python-3.6.9 torch-1.8.0 CUDA:0 (NVIDIA Tegra X1, 3964MiB)



WARNING ⚠️ Python 3.7.0 is required by YOLOv5, but Python 3.6.9 is currently installed


Fusing layers... 
YOLOv5s summary: 213 layers, 7012822 parameters, 0 gradients, 15.8 GFLOPs
Adding AutoShape... 


In [4]:
# 本格為觀察測試相片檔的格式

import cv2

img = cv2.imread('./test_imgs/5cockroaches.jpg')

print(img[:2])

[[[159 127 152]
  [158 126 151]
  [161 126 153]
  ...
  [192 146 168]
  [193 147 169]
  [193 147 169]]

 [[157 125 150]
  [159 127 152]
  [164 129 156]
  ...
  [192 146 168]
  [192 146 168]
  [192 146 168]]]


In [3]:
# 使用相片來做模型性能檢測

img_1 = './test_imgs/5cockroaches.jpg'

img_2 = './test_imgs/3cockroaches.jpg'

img_3 = './test_imgs/1cockroach.jpg'

img = [img_1, img_2, img_3]

results = model(img, size=640)

results.print()

image 1/3: 640x640 5 cockroachs
image 2/3: 640x640 3 cockroachs
image 3/3: 640x640 1 cockroach
Speed: 111.6ms pre-process, 251.7ms inference, 136.3ms NMS per image at shape (3, 3, 640, 640)


In [4]:
# 顯示結果圖片
results.show()

# 儲存結果圖片
# results.save()

In [4]:
print(type(results.pandas()))
print(results.pandas()) # similiar to results.print()

<class 'models.common.Detections'>
image 1/3: 640x640 5 cockroachs
image 2/3: 640x640 3 cockroachs
image 3/3: 640x640 1 cockroach
Speed: 111.6ms pre-process, 251.7ms inference, 136.3ms NMS per image at shape (3, 3, 640, 640)


In [5]:
print(type(results.pandas().xyxy))
results.pandas().xyxy

<class 'list'>


[         xmin        ymin        xmax        ymax  confidence  class  \
 0  207.430054  329.806702  316.076477  476.015259    0.979864      0   
 1  311.979156  367.455566  374.265045  458.926941    0.968334      0   
 2  283.701477  537.404480  347.313232  633.743225    0.963639      0   
 3  344.364471  535.396790  433.650665  590.953674    0.918541      0   
 4  398.444672  441.185120  479.062286  498.900208    0.859740      0   
 
         name  
 0  cockroach  
 1  cockroach  
 2  cockroach  
 3  cockroach  
 4  cockroach  ,
          xmin        ymin        xmax        ymax  confidence  class  \
 0   38.721588  405.205261  186.911163  570.466919    0.981878      0   
 1  283.064148  264.411957  352.872009  355.525604    0.967315      0   
 2  209.250183  350.465637  581.949829  601.244812    0.963974      0   
 
         name  
 0  cockroach  
 1  cockroach  
 2  cockroach  ,
         xmin        ymin        xmax        ymax  confidence  class       name
 0  10.204041  216.17892

In [6]:
for i in results.pandas().xyxy:
    print(i)
    print('-' * 50)

         xmin        ymin        xmax        ymax  confidence  class  \
0  207.430054  329.806702  316.076477  476.015259    0.979864      0   
1  311.979156  367.455566  374.265045  458.926941    0.968334      0   
2  283.701477  537.404480  347.313232  633.743225    0.963639      0   
3  344.364471  535.396790  433.650665  590.953674    0.918541      0   
4  398.444672  441.185120  479.062286  498.900208    0.859740      0   

        name  
0  cockroach  
1  cockroach  
2  cockroach  
3  cockroach  
4  cockroach  
--------------------------------------------------
         xmin        ymin        xmax        ymax  confidence  class  \
0   38.721588  405.205261  186.911163  570.466919    0.981878      0   
1  283.064148  264.411957  352.872009  355.525604    0.967315      0   
2  209.250183  350.465637  581.949829  601.244812    0.963974      0   

        name  
0  cockroach  
1  cockroach  
2  cockroach  
--------------------------------------------------
        xmin        ymin  

In [7]:
results.pandas().xyxy[0]

xmin        ymin        xmax        ymax  confidence  class  \
0  207.430054  329.806702  316.076477  476.015259    0.979864      0   
1  311.979156  367.455566  374.265045  458.926941    0.968334      0   
2  283.701477  537.404480  347.313232  633.743225    0.963639      0   
3  344.364471  535.396790  433.650665  590.953674    0.918541      0   
4  398.444672  441.185120  479.062286  498.900208    0.859740      0   

        name  
0  cockroach  
1  cockroach  
2  cockroach  
3  cockroach  
4  cockroach

In [9]:
matching_df = results.pandas().xyxy[0]

filter = (matching_df['name'] == 'cockroach')
matching_df = matching_df[filter]
print(matching_df)
matching_detections = matching_df.loc[0]
print(matching_detections)

         xmin        ymin        xmax        ymax  confidence  class  \
0  207.430054  329.806702  316.076477  476.015259    0.979864      0   
1  311.979156  367.455566  374.265045  458.926941    0.968334      0   
2  283.701477  537.404480  347.313232  633.743225    0.963639      0   
3  344.364471  535.396790  433.650665  590.953674    0.918541      0   
4  398.444672  441.185120  479.062286  498.900208    0.859740      0   

        name  
0  cockroach  
1  cockroach  
2  cockroach  
3  cockroach  
4  cockroach  
xmin             207.43
ymin            329.807
xmax            316.076
ymax            476.015
confidence     0.979864
class                 0
name          cockroach
Name: 0, dtype: object


In [10]:
len(results.pandas().xyxy[0].index)

5

In [11]:
results.pandas().xyxy[1]

xmin        ymin        xmax        ymax  confidence  class  \
0   38.721588  405.205261  186.911163  570.466919    0.981878      0   
1  283.064148  264.411957  352.872009  355.525604    0.967315      0   
2  209.250183  350.465637  581.949829  601.244812    0.963974      0   

        name  
0  cockroach  
1  cockroach  
2  cockroach

In [12]:
results.pandas().xyxy[2]

xmin        ymin        xmax        ymax  confidence  class       name
0  10.204041  216.178925  114.700584  270.481476    0.968994      0  cockroach

In [14]:
from IPython.display import display
import ipywidgets.widgets as widgets

detections_widget = widgets.Textarea()

detections_widget.value = str(results.pandas().xyxy[0])

display(detections_widget)

Textarea(value='         xmin        ymin        xmax        ymax  confidence  class  \\\n0  207.430054  329.8…

In [15]:
# 第一張照片的所有BBOX資訊
detections_0 = results.pandas().xyxy[0]
# print(detections_0)
# print(type(detections_0))  # <class 'pandas.core.frame.DataFrame'>

class_name = detections_0['name']
print(class_name)
print("-" * 50)

xmin = detections_0['xmin']
print(xmin)
print("-" * 50)

detections_0

0    cockroach
1    cockroach
2    cockroach
3    cockroach
4    cockroach
Name: name, dtype: object
--------------------------------------------------
0    207.430054
1    311.979156
2    283.701477
3    344.364471
4    398.444672
Name: xmin, dtype: float64
--------------------------------------------------


xmin        ymin        xmax        ymax  confidence  class  \
0  207.430054  329.806702  316.076477  476.015259    0.979864      0   
1  311.979156  367.455566  374.265045  458.926941    0.968334      0   
2  283.701477  537.404480  347.313232  633.743225    0.963639      0   
3  344.364471  535.396790  433.650665  590.953674    0.918541      0   
4  398.444672  441.185120  479.062286  498.900208    0.859740      0   

        name  
0  cockroach  
1  cockroach  
2  cockroach  
3  cockroach  
4  cockroach

In [15]:
# 預設取出資料已透過confidence做降冪排序, 不需要額外排序

print(detections_0.sort_values(by='confidence', ascending=False))

         xmin        ymin        xmax        ymax  confidence  class  \
0  207.430054  329.806702  316.076477  476.015259    0.979864      0   
1  311.979156  367.455566  374.265045  458.926941    0.968334      0   
2  283.701477  537.404480  347.313232  633.743225    0.963639      0   
3  344.364471  535.396790  433.650665  590.953674    0.918541      0   
4  398.444672  441.185120  479.062286  498.900208    0.859740      0   

        name  
0  cockroach  
1  cockroach  
2  cockroach  
3  cockroach  
4  cockroach  


In [16]:
# 取出第一張照片中confidence最高的BBOX資訊
HighestConfidenceResult = detections_0.loc[0]
print(HighestConfidenceResult)
# print(type(HighestConfidenceResult))  # <class 'pandas.core.series.Series'>

xmin             207.43
ymin            329.807
xmax            316.076
ymax            476.015
confidence     0.979864
class                 0
name          cockroach
Name: 0, dtype: object


In [27]:
xmin = int(HighestConfidenceResult['xmin'])
xmax = int(HighestConfidenceResult['xmax'])
print(xmin)
print(xmax)

ymin = int(HighestConfidenceResult['ymin'])
ymax = int(HighestConfidenceResult['ymax'])
print(ymin)
print(ymax)

print(type(HighestConfidenceResult['xmin']))
print(type(xmin))

207
316
329
476
<class 'numpy.float64'>
<class 'int'>


In [35]:
# 找出中心點的x
w = xmax - xmin
central_x = int(xmin + (w/2))
print(central_x)

261


In [36]:
# 找出中心點的y
h = ymax - ymin
central_y = int(ymin + (h/2))
print(central_y)

402


In [39]:
### circle : cv2.circle ( 影像, 圓心座標, 半徑, 顏色, 線條寬度 )
### 確定xmin, xmax, ymin, ymax點的位置

import cv2

gc = cv2.imread('./test_imgs/5cockroaches.jpg')

gc = cv2.circle(gc, (xmin, ymin), 10, (255, 255, 0), 4)  # (xmin, ymin) = bbox 左上角
cv2.imwrite('./01.jpg', gc)

True

In [40]:
gc = cv2.imread('./test_imgs/5cockroaches.jpg')

gc = cv2.circle(gc, (xmax, ymax), 10, (255, 255, 0), 4)  # (xmax, ymax) = bbox 右上角
cv2.imwrite('./02.jpg', gc)

True

In [43]:
import numpy as np

gc = cv2.imread('./test_imgs/5cockroaches.jpg')

gc = cv2.circle(gc, (central_x, central_y), 10, (255, 255, 0), 4)
cv2.imwrite('./03.jpg', gc)

True

In [66]:
image_number = 0
object_number = 0

a = results.pandas().xyxy[image_number].loc[object_number]
print(a)
print("-" * 50)
print("xmin:", round(results.pandas().xyxy[image_number].loc[object_number]['xmin'], 2))

xmin             207.43
ymin            329.807
xmax            316.076
ymax            476.015
confidence     0.979864
class                 0
name          cockroach
Name: 0, dtype: object
--------------------------------------------------
xmin: 207.43
